### ISSUE TITLE
Názvy malých dolín

### ISSUE THREAD

**Issue by synalik** [FreemapSlovakia/freemap-mapnik#101]
Nazov malych dolin sa zobrazuje daleko - casto na ich bocnych hrebenoch. 
Priklad: - https://www.freemap.sk/?map=17/49.105506/19.222679&layers=X
https://www.freemap.sk/?map=17/49.133127/19.298150&layers=X

_poznámka od - Mirecnet_

**Comment by Mirecnet** [comment]
Casto aj o dolinu dalej, co na mapu zle zobrazenie https://www.freemap.sk/?map=16/48.986948/19.200046&layers=X

**Comment by pdragun** [comment]
Príklad z Vysokých Tatier: Téryho kuloár sa zobrazuje úplne inde: https://www.freemap.sk/?map=16/49.192937/20.214264&layers=X

**Comment by zdila** [comment]
kludne navrhni konkretne pravidla na renderovanie aby nazvy dolin neprekryvali features ktore casto vedu ich stredom (vodne toky, cesty, obce...) ak by nazvy boli renderovane stredom. Potom niektori mapperi maju tendenciu mapovat pre renderrer - tj posuvat ciaru doliny mimo stred.
