### ISSUE TITLE
Rendrovanie skol, nemocnic, druzstiev nad vrstvou obce

### ISSUE THREAD

**Issue by misko903** [FreemapSlovakia/freemap-mapnik#111]
Rendrovanie skol, nemocnic, druzstiev by malo byt pravdepodobne nad vrstvou obce , ako je to na starom freemape.

Miso

**Comment by zdila** [comment]
priklad miesta kde tomu tak nie je?

**Comment by misko903** [comment]
PD Velka Hradna
https://www.freemap.sk/?map=16/48.769856/18.135960&layers=X
ako to vyzera v OSM rendereri:
https://www.openstreetmap.org/#map=16/48.7699/18.1351

Dubodiel skola:
https://www.freemap.sk/?map=17/48.762839/18.111348&layers=X
 Cuklasovce PD
https://www.freemap.sk/?map=16/48.739506/18.139217&layers=X
atd...

miso


št 15. 8. 2019 o 22:04 Martin Ždila <notifications@github.com> napísal(a):

**Comment by zdila** [comment]
Farmyard som uz prehodil a rendering arealu skoly nie je naimplementovany.

**Comment by misko903** [comment]
Stale rovnako:
https://www.freemap.sk/?map=17/48.770965/18.129390&layers=X

miso


pi 16. 8. 2019 o 8:15 Martin Ždila <notifications@github.com> napísal(a):

**Comment by zdila** [comment]
Este to nebolo nasadene kedze to vyzaduje reimport. Mozno do konca roka alebo ak niekto zafinancuje.
