### ISSUE TITLE
Biela ciara cez mapu

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemap-mapnik#113]
Vsimol som si bielu ciaru v mape Freemap X. Nieje to daka chyba ?

Velka vyrazna ciara
https://www.freemap.sk/?map=15/49.015968/19.650551&layers=X
https://www.freemap.sk/?map=15/49.186338/19.648631&layers=X
Male nevyrazne stvorce
https://www.freemap.sk/?map=18/49.201507/19.643342&layers=X

Prosim pozrite sa na to. Dakujem.

**Comment by tjamecny** [comment]
Vyzerá to byť problém vo výškových dátach, napr. pri spájaní dvoch susedných súborov (aj keď si nie som úplne istý, či tie súbory sú delené presne podľa poludníkov). Je to vidieť hlavne na vrstevniciach, ako skáču zo strany na stranu:

![obrázok](https://user-images.githubusercontent.com/16599347/64555124-f5fce180-d33c-11e9-99a9-b8d17189c23e.png)

**Comment by Mirecnet** [comment]
Vyzera to naozaj tak, lebo biela ciara ide vertikalne cez cele hornate Slovensko. Problem je poriadne zavazny, lebo biela ciara skutocne vertikalne prechadza cez cele Slovensko.

Biela ciara zacina uz na Orave pri Zabiedove vo vyske 700 m.n.m. az 900  m.n.m. pri Habovke. Pokracuje pri Zuberci v 1050 m.n.m., na Sivom vrchu sa straca a objavuje sa znova na Ostrej v 1650 m.n.m., popri chate na Cervenci v 1500 m.n.m. a straca sa niekde vo vyske 800 m.n.m. v Bobroveckej doline. Matne je viditelny nad Liptovskym Mikulasom v Hajci na vrstevnici 700 m.n.m. Potom zmizne a objavuje sa pri Zavaznej Porube v 680 m.n.m. Krizuje Krakovu holu, kde sa vsak v 1600 m.n.m. strati a znova pokracuje v 1350 m.n.m. na Dumbier v 2000 m.n.m. Nasledne sa pri Jaskyni Mrtvych Netopierov strati v 1500 m.n.m. Potom sa striedavo objavuje na Kozich chrbtoch v 1650 az 1500 m.n.m, 1200 m.n.m. az konci v 650 m.n.m. v Myte pod Dumbierom. Matne pokracuje ponad Brezno pri baniach na Tobernit 800-550 m.n.m. a znova sa matne objavuje za Breznom vo vyske 550-650-700 m.n.m., kde konci v Ciernom Balogu. Stale ju vsak matne vidno pri Sihle a prameni Ipla. Znova sa objavuje pri Detvianskej Hute-Latky vo vyske 900 m.n.m. a striedavo pokracuje popri vodnej nadrzi Malinec 800-750 m.n.m., klesa na 450 m.n.m. a znova sa matne ukazuje pri Sutovej jame v 700 m.n.m. Matne prechadza  aj cez Cinobanu v 300 m.n.m. a konci pred Lucencom vo vyske 200 m.n.m. 

Ako sa stratia vrstevnice na juh do Madarska a na sever do Polska, tak sa ciara konci.
Problem je len vo vrstevniciach na vrstve X.  Pri T vrvste sa tento problem neprejavuje.

**Comment by zdila** [comment]
> Problem je poriadne zavazny

blocker :-D
