### ISSUE TITLE
render railway=abandoned

### ISSUE THREAD

**Issue by misko903** [FreemapSlovakia/freemap-mapnik#123]
Ahoj,
odkedy som zmenil railway=disused na railway=abandoned, nerenderuje sa.
mozno by stacilo renderovat to tak isto ako disused.

robi to aj na locus teme
vdaka,
Miso

**Comment by zdila** [comment]
railway=abandoned znamena ze tam uz kolajnice fyzicky nie su, takze sa ani nerenderuju.

**Comment by misko903** [comment]
aha, tak retagujem naspat. vdaka.
