### ISSUE TITLE
Posedy ako  otázniky

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-mapnik#130]
zoome 14 sa renderujú posedy ako ?
má to tak byť?

v strede mapy: https://www.freemap.sk/?map=14/48.685068/17.865057&layers=X

**Comment by zdila** [comment]
otaznik sa renderuje ak je tam tag `fixme` a je to od zoomu 14

posedy sa renderuju od zoomu 15 a maju vyssiu prio ako otazniky.
