### ISSUE TITLE
render ford=yes

### ISSUE THREAD

**Issue by misko903** [FreemapSlovakia/freemap-mapnik#131]
vyborne na outdoor mape by bolo rendrovanie brodov. kde su, snazim sa ich znacit.
vdaka!

**Comment by zdila** [comment]
po nasadeni to bude takto:

![image](https://user-images.githubusercontent.com/636095/152231755-a2a46845-39f7-495a-9c33-a3bb9c0b91e1.png)

**Comment by misko903** [comment]
Pekné, super, vďaka!

Dňa st 2. 2. 2022, 21:26 Martin Ždila ***@***.***> napísal(a):
