### ISSUE TITLE
Zákaz vjazdu motorových vozidiel

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-mapnik#136]
Všimol som si že sa asi nijak nerenderujú zákazy vjazdu motorových vozidiel. Iba peších a cyklistov.
https://www.freemap.sk/?map=18/49.298378/16.579828&layers=XI&tool=photos&image=249746
https://www.openstreetmap.org/way/299835827#map=17/49.30120/16.58202&layers=D

**Comment by zdila** [comment]
Toto neplanujem. Je to outdoorova mapa - pohyb na bicykli, peso, bezky, kon... Pre auta su urcene ine mapy.

**Comment by seg-on** [comment]
ok
