### ISSUE TITLE
Render water_slide

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-mapnik#137]
Here's a nice example:
https://www.freemap.sk/?map=20/47.983319/17.607826&layers=O
vs
https://www.freemap.sk/?map=20/47.983319/17.607826&layers=X

**Comment by zdila** [comment]
![image](https://user-images.githubusercontent.com/636095/99112303-c0612180-25ed-11eb-83bb-570abb3713f0.png)
