### ISSUE TITLE
Render highway=via_ferrata

### ISSUE THREAD

**Issue by kaylesk** [FreemapSlovakia/freemap-mapnik#139]
Viď napr. https://www.freemap.sk/?map=17/49.088237/18.834665&layers=X
V mapsfrorge som to dal "čiarkovano", ale vyzerá to ako železničná trať, takže to bude nejak inak vyzerať. (Len ešte neviem ako.)
![obrázok](https://user-images.githubusercontent.com/8353866/88175157-c2aa0500-cc25-11ea-9a6c-746fae05e221.png)

**Comment by zdila** [comment]
ja cca tak, pripomina to mozno retaz:

![image](https://user-images.githubusercontent.com/636095/99110082-1d5ad880-25ea-11eb-8221-a109b045e1bb.png)
