### ISSUE TITLE
Odlíšiť dočasné vodné plochy

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-mapnik#140]
Ak by sa dalo, odlíšiť občasné vodné plochy od celoročne zaplavených.
https://www.openstreetmap.org/changeset/30407284#map=16/48.0269/18.2275

**Comment by seg-on** [comment]
Napr podobne ako to má Mapbox
https://www.freemap.sk/?map=15/48.029514/18.223915&layers=O

**Comment by zdila** [comment]
![image](https://user-images.githubusercontent.com/636095/99147722-77f44300-2683-11eb-99ca-3e0080d983d0.png)
