### ISSUE TITLE
Piktogram k trase

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-mapnik#148]
Toto je len idea. Či nepridať k značkovaným trasám (možno iba niektorým typom) pri väčších zoomoch ~17-18 piktogram naznačujúci tip športu. Podobne ako je pridaný text, či číslo trasy.
Možno to dať pred číslo trasy napr.
Človek rýchlo zabudne že napr cikcak čiara je bežkárska a pri veľkom zoome by to nemuselo byť až také rušivé a všimol som si že keď ľudia nevedia zoomujú či sa neobjaví nejaký ďalší vysvetlujúci detail.

**Comment by zdila** [comment]
Na to ma sluzit legenda mapy.
