### ISSUE TITLE
Render millitary zone

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-mapnik#15]

**Comment by petervojtek** [comment]
mne sa paci tento pristup:
https://opentopomap.org/#map=12/48.3524/17.1469
https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/styles-otm/areas.xml

**Comment by zdila** [comment]
Ano, urcite srafovanie. Ale dal by som ho este jemnejsie od OTM. A od isteho zoomu ho nezobrazoval, kedze do mnohych takych oblasti je vstup povoleny podla rozvrhu a tazsie sa potom pouziva takto srafovana mapa.

**Comment by petervojtek** [comment]
Martin @zdila , spravil som zatial aspon takyto zaklad:

<img width="626" alt="screenshot 2019-01-20 at 15 19 14" src="https://user-images.githubusercontent.com/225506/51440797-fb80bb00-1cca-11e9-9217-00a21a8d3dd4.png">
<img width="714" alt="screenshot 2019-01-20 at 15 19 23" src="https://user-images.githubusercontent.com/225506/51440799-fb80bb00-1cca-11e9-9bb0-807d96072790.png">
<img width="840" alt="screenshot 2019-01-20 at 15 19 34" src="https://user-images.githubusercontent.com/225506/51440800-fb80bb00-1cca-11e9-9e4a-15c7b205f588.png">

a od Z14 uz nie je srafovanie
<img width="999" alt="screenshot 2019-01-20 at 15 19 47" src="https://user-images.githubusercontent.com/225506/51440801-fc195180-1cca-11e9-8b82-8da4752efe8a.png">


nepodarilo sa mi vyrobit ten pattern tak ako by som si zelal v svg, tak som zatial z nudze pouzit ten z OTM (png). samotne nazvy zon rendrovane nie su.

**Comment by zdila** [comment]
Prehodil som to na svg a dal do mastra.

![image](https://user-images.githubusercontent.com/636095/51444722-8b3e5d80-1cfb-11e9-99b9-d9e53802fef2.png)

Pozeram ze este tam dam priesvitnost. Inac mozno by bolo potom lepsie to dat na vyssiu vrstvu, lebo napr teraz cesty, potoky, POI, labels su nad.

**Comment by zdila** [comment]
> Pozeram ze este tam dam priesvitnost.

Hotovo

> Inac mozno by bolo potom lepsie to dat na vyssiu vrstvu, lebo napr teraz cesty, potoky, POI, labels su nad.

Upravil som vrstvenie.

**Comment by zdila** [comment]
Nakoniec som dal srafovanie aj na vyssie zoomy, ale s velkou priesvitnostou. Predsalen, nech si clovek stale uvedomuje ze moze vychytat zbludilu gulku ci minu ;-)

**Comment by petervojtek** [comment]
ok, vdaka za pomoc.
