### ISSUE TITLE
Renderovanie skal v uavretom polygone

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemap-mapnik#155]
Vsimol som si, ze na vrstve X sa nerenderuju uzavrete polygony skal. Otvoreny polygon skaly sa normalne zobrazi, ale ak je to velka skala uzavreta v jednom polygone, tak sa nezobrazuje.

Pekne to vidno napriklad v skalach na vrchu Sip: 
(OK) > T: https://www.freemap.sk/?map=18/49.165132/19.184634&layers=T
(ZLE) > X: https://www.freemap.sk/?map=18/49.165132/19.184634&layers=X

Pozrite sa na to prosim.

**Comment by zdila** [comment]
docasne pomoze pridat tag `area=no`

**Comment by Mirecnet** [comment]
Dakkujem, tag area=no 
funguje

X: https://www.freemap.sk/?map=18/49.165132/19.184634&layers=X

**Comment by zdila** [comment]
fixed in 2c8f4ff834e690ca49f9ca905e5d997f6928ba8a
