### ISSUE TITLE
Spring icons

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-mapnik#157]
At the moment, all types of springs are rendered the same, regardless of their importance. In a [discussion on the osm forum](https://groups.google.com/d/msg/osm_sk/j9cH2lMfzuE/vuxvViv4BAAJ) it was suggested that there are (roughly speaking) two classes of springs, and that it might be beneficial to render them differently on the map.
1. **important** springs, that are named, and/or have additional tags besides the standard natural=spring. In particular, these tags were mentioned:
- drinking_water=yes
- refitted=yes
- man_made=spring_box
2. **common** springs - all of the other ones, typically without additional tags besides the natural=spring one.

Regarding rendering, two icons - or the same icon with different colors - might be used to differentiate these objects on the map. My feeling is that using a lighter shade of blue for the category 2 springs should be sufficient and less confusing than using completely different icons for the two categories.

**Comment by Mirecnet** [comment]
Pramene su vyrazne aj na OSM a nieje dovod ich v prirode schovavat. 
https://www.openstreetmap.org/#map=14/48.9637/19.3583
Mapy.cz s tym tiez problem namaju
https://sk.mapy.cz/zakladni?x=19.3439070&y=48.9478628&z=16

Pramen rieky a potoka je vyznamna cast mapy, ktoru komercne projekty obycajne nemaju.

Skor by som navrhoval daku peknu ikonu pre studnicku.
Nieco taketo napriklad:
https://images.app.goo.gl/iYBmAM2RjKP5eRL89
http://studnicky.novabana.sk/

Ikona: Strieska a pramen.

pri tagu: 
drinking_water=yes - pitna voda
refitted=yes - pramen upraveny ludmi

Skatka daka pekna ikona, ktora ma vypovedny udaj o zaujimavom prameni. Tam kde sa da spokojne napit, ked vam dojde voda a pokojne to moze byt aj nenarocny ciel vyletu.
Nieco take, co Mapy.cz skratka nemaju :)

**Comment by alexanderzatko** [comment]
Miro, IMHO vo vacsine pripadov nema zmysel tagovat zaciatky tokov tagom pramen, pretoze tato informacia je implicitne obsiahnuta vo fakte, ze draha vodneho toku ma smer a teda ten nod ktory uz nema predchodcu je pramen. Ak by aj napriek tomu kartograf chcel, aby vsetky potoky zacinali ikonkou pramen, tak jednoducho urobi program ktory tie pociatky tokov najde sam a nahradi ten prvy nod ikomnou pramen.

Osobne teda povazujem oznacovanie beznych ("common") pociatkov tokov ikonkou pramen za zbytocne ked maju vyznaceny sipkou smer toku, a to aj preto, lebo je tak na mape zbytocne vela znaciek. Ja by som teda tieto bezne pramene ani na mape nezobrazoval. Kompromisne riesenie je to, co navrhujem hore - ze ikony beznych pramenov z mapy neodstranovat, ale ich urobit menej vyrazne.

Cize dolezite pramene mozu byt zobrazene, alebo aj zobrazene vyraznejsie, pripadne podkategorie dolezitych pramenov mozu mat speci ikony - napriklad zastreseny pramen s pitnou vodou moze mat ikonu aku navrhujes ty.

**Comment by zdila** [comment]
![image](https://user-images.githubusercontent.com/636095/99149366-d8887d80-268d-11eb-9322-2639095c4416.png)
![image](https://user-images.githubusercontent.com/636095/99149370-df16f500-268d-11eb-9ea9-ada1c063ea84.png)
