### ISSUE TITLE
Cyklocesta - smer

### ISSUE THREAD

**Issue by PertR** [FreemapSlovakia/freemap-mapnik#162]
Na V5 sa to ako tak ukaze, ale na webe freemap.sk  smer nevidiet. 

Vsimol som si aj, ze ten smer jazdy nie je vidiet ani v openstreetmap.org 
 pri prepnuti  cyklovrstvy. Vidiet to len pri standardnej vrstve. S tymto asi nic neurobime, akurat by sme mohli prist na sposob,ako tu cestu vyrobit,aby to bolo vidiet aj v cyklo vrstve.(mozno to potom automaticky naskoci aj vo freemaps.sk )

**Comment by zdila** [comment]
duplikuje #109
