### ISSUE TITLE
Render leisure=sauna

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-mapnik#163]
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dsauna

https://www.freemap.sk/?map=19/48.989030/20.634752&layers=O

**Comment by zdila** [comment]
@seg-on skus pripravit pull-request

**Comment by seg-on** [comment]
skúsil som

**Comment by zdila** [comment]
nevidim ho tam :-)

**Comment by zdila** [comment]
checklist:
- [ ] pripravit ikonu
- [ ] dat do `mapping.yml` (co si bude vyzadovat reimport)
- [ ] dat do `additional.sql`
- [ ] dat do `style/index.js`

vsetko v `develop`

**Comment by seg-on** [comment]
už by to tam mohol byť. učím sa s tým robiť a ešte tomu úplne nerozumiem :)
