### ISSUE TITLE
Názvy dolín/hrebeňov vo VT splývajú s tieňovaním

### ISSUE THREAD

**Issue by pdragun** [FreemapSlovakia/freemap-mapnik#183]
Po pridaní "lidar" tieňovania nie sú názvy dolín/hrebeňov dostatočne viditeľné: príklad doliny Téryho kuloár: https://www.freemap.sk/?map=16/49.192937/20.214264&layers=X v prípade väčšieho zoomu je to ešte horšie: https://www.freemap.sk/?map=17/49.192902/20.213320&layers=X

**Comment by zdila** [comment]
navrh riesenia? aby zas na hladsiom terene to nebolo prilis vyrazne.

mimochodom nemam problem precitat _Téryho kuloár_ na https://www.freemap.sk/?map=16/49.192937/20.214264&layers=X.

pri vacsiom zoome zas nemam problem odzoomovat.

**Comment by zdila** [comment]
zatvaram vzhladom n vyhladenie tienovania
