### ISSUE TITLE
Make shaded relief more plastic

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-mapnik#19]
@didoa vedel by si prosim s tymto pomoct - ake parametre boli pouzite v `gdaldem hillshade` pripadne inom toole?

**Comment by didoa** [comment]
pouzil som maperitive a kombinaciu 3-4 reliefov cez seba, tzv.  swiss topo style  ci alpenglow ci tak dajako

http://www.reliefshading.com/colours/grey/
http://www.reliefshading.com/colours/yellow-tone/

na generovanie bol pouziti nejaky alg., "relieg-gen-igor" co je nejaky alg. co vyrobil autor maperitive-u Igor Brejc. nieco podobne tomuto

http://braincrunch.tumblr.com/post/26190799580/maperitive-alpenglow-effect-using-a-custom-shader

----tu su dve verzie skriptu, jeden je do z14, druhy z15+(alebo opacne)

generate-relief-igor intensity=0.8 sun-azimuth=325 sun-altitude=20 color=#275F9C sample-rate=1 
generate-relief-igor intensity=0.4 sun-azimuth=45 sun-altitude=35 color=#FFEE00 sample-rate=1 
generate-relief-igor intensity=1  sample-rate=1
generate-relief-slopeshading intensity=0.6  sample-rate=1

vs. 

generate-relief-igor intensity=0.4 sun-azimuth=325 sun-altitude=20 color=#275F9C sample-rate=1 
generate-relief-igor intensity=0.3 sun-azimuth=45 sun-altitude=35 color=#FFEE00 sample-rate=1 
generate-relief-igor intensity=0.6  sample-rate=1
generate-relief-slopeshading intensity=0.3  sample-rate=1

proste som sa stym dost hral, ked bol cas a ine :)

**Comment by zdila** [comment]
Vdaka Uvidim ako to budem vediet zuzitkovat :)

**Comment by zdila** [comment]
@didoa nakoniec si rovno z toho generoval tiles pomocou prikazu `generate-tiles`? A priamo pre celu oblast (bbox v ktorom je cele slovensko)? A robil si to priamo v GUI alebo nejakym skriptom? Lebo ked vygenerujem ten shading tak GUI je znacne pomale.

**Comment by zdila** [comment]
Viacmenej hotovo za pouzitia uz existujuceho tienovania, hoci idealne by bolo mat lahko zreprodukovatelny rendering.

**Comment by zdila** [comment]
Inac mne Maperitive uplne ignoruje parameter `sun-altitude` a dava tam odhadom na tvrdo tak 70 az 80.

**Comment by zdila** [comment]
Tu je este zaujimavy sposob generovania pomocou custom shadera pre Maperitive: http://braincrunch.tumblr.com/post/26190799580/maperitive-alpenglow-effect-using-a-custom-shader

**Comment by zdila** [comment]
https://github.com/OSGeo/gdal/issues/1330
