### ISSUE TITLE
Nazov kopca Velky Choc nie je vidno

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-mapnik#199]
Objavi sa az pri zoom > 19

https://www.freemap.sk/?map=19/49.150949/19.343834&layers=X

**Comment by zdila** [comment]
Je aj na zoome 9 a 10, na z11 a z12 vidis razcestnik (ma vyssiu priority ako vrchol), a na dalsich zoomoch su dalsie prioritnejsie veci pre dany zoom.

**Comment by alexanderzatko** [comment]
vsak to - tie priority...

**Comment by zdila** [comment]
keby mal kopec max prioritu, tak na nom nemusis nikdy uvidiet napr ze je tam razcestnik, vyhlad, a rozne ine POI, resp len pri velkych zoomoch.

teraz je to tak ze napr nazov kopca uvidis pri nizsich zoomoch, a potom ked zoomujes chces vidied dalsie detaily. keby ich kopec prebil, tak by si musel velmi zoomovat, ak by to vobec pomohlo.

**Comment by alexanderzatko** [comment]
Nikdy som podrobne nestudoval ako riesit umiestnovanie stitkov na mapach, ale predpokladal by som, ze vymysliet na to algoritmus nie je lahke. - taky algoritmus, ktory by bol v sulade s ocakavanim vacsiny pouzivatelov map.

Moj osobny nazor - ktory sa moze lisit od predstavy tej vacsiny - je ten, ze umiestnovanie stitkov prinajmensom v pripade tohoto kopca nie je optimalne. Nemusi sa mu preto prikladat velka vaha (mojmu nazoru).

Budem trochu konkretnejsi, opisem len par zoomov:

- na z16 chybaju akekolvek stitky, okolo vrcholu su symboly rozlicnych POI, napriklad vyhladove tam vidim 4 + jednu ikonu pre pamatnik. Asi by stacila jedna ikona pre vyhlad (aby pouzivatel videl ze tam nejaky vyhlad najde) + meno kopca.
- nz z17 dominuje mape stitok "Spominame na Jozefa", ale aspon je uz vidiet trojuholnicek indikujuci kde sa nachadza (nejaky) vrchol. Ak by stitky na (analogovu) mapu v tomto rozliseni boli umiestnovane manualne, tak by kartograf asi umiestnil nazov kopca na SV od ikonky trojuholnika
- z18 stale nevieme kde je vlastne vrchol Choca, su tam konfliktne informacie ako "Vrchol Choca", pri ikonke, ktora vyzera ako hranicny kamen (.. a take su tam hned dve, ale s tym sa asi nic neda robit, ked su dva aj v terene). Ten "spominame na Jozefa" text z pamatnika tam stale vidime, vsetkemu dominuje stitok turistickeho razcestnika. Ikonku skutocneho vrchola bez stitka v tomto zmatku pozorovatel moze lahko opomenut, alebo ju povazovat za nejaky bezvyznamny predvrchol kopca.

Viem si predstavit ze riesenim na tento problem by mohla byt specialne vytrenovana ANN a podla google search tato domnienka nemusi byt nespravna.

https://www.google.com/search?client=firefox-b-d&q=map+labels+placement+with+machine+learning

**Comment by zdila** [comment]
mozno v niektorych pripadoch pomoze #201
