### ISSUE TITLE
Issue with rendering viewpoint

### ISSUE THREAD

**Issue by pedjas** [FreemapSlovakia/freemap-mapnik#204]
Here is the viewpoint that is not rendered on the map: https://www.openstreetmap.org/node/5607474622

It is tagged as tower with platform which is used as viewpoint.

Here is complete tagging:

access=public
man_made=tower
name=Видиковац Сјенич
name:en=Sjenič Vidikovac (watchtower)
tourism=viewpoint
tower:construction=freestanding
tower:type=observation
viewpoint=platform

**Comment by zdila** [comment]
This project is not about map on https://www.openstreetmap.org/ but about map on https://www.freemap.sk/?map=17/43.922267/19.323851&layers=X where you can see the tower.

**Comment by pedjas** [comment]
Sure, but I edit OpenStreetMap, and you get those data for rendering. I posted link to original OSM data.

Yes, now object is visible. At the moment I posted this, it was not there. Other objects around it that I entered on the map at the same time or later were visible but not this one. That is why I thought it was something about rendering.

Now, all is good.
