### ISSUE TITLE
Zdvojené renderovanie názvov

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-mapnik#209]
https://www.freemap.sk/?map=14/48.181196/17.064600&layers=Xn2t

![obrázok](https://user-images.githubusercontent.com/1406222/134293215-0f04ef51-01ea-4bca-a113-54181aeb99b4.png)

Taketo zdvojene (obcas mierne sa prekryvajuce) nazvy neposobia velmi esteticky.

Podobny problem len mozno viditelnejsi napr. aj tu:

https://www.freemap.sk/?map=13/48.385328/20.025845&layers=Xn2t

![obrázok](https://user-images.githubusercontent.com/1406222/134293390-dbf25a1c-5ad5-4a96-a649-ab12faf18a9c.png)

**Comment by zdila** [comment]
Vypni si vrstvy co mas naviac pozapinane:

![image](https://user-images.githubusercontent.com/636095/134293663-08b14659-f723-4b0e-b598-5e5f1f818cb1.png)

**Comment by jose1711** [comment]
diky. na vrstvy som totiz klikal a nenapadlo mi, ze treba rozkliknut "Ukazat vsetky vrstvy" (a pole na URL mam prilis kratke na to, aby som dovidel az na koniec)

![obrázok](https://user-images.githubusercontent.com/1406222/134297301-f906c677-2905-45b7-b355-e1913dcd0a38.png)

nebolo by lepsie, keby aktivne vrstvy boli zobrazovane vzdy? ak treba, spravim novu issue.

**Comment by zdila** [comment]
mam to v plane nejako indikovat

**Comment by tjamecny** [comment]
Navrhoval by som aktivne vrstvy umiestnovat este pred polozku "Ukazat vsetky vrstvy", napr. miesto tych Strava* poloziek. Vtedy uzivatel vidi hned, co ma pozapinane a nemusi rozklikat vsetky vrstvy.

**Comment by jose1711** [comment]
hmm... implementovane? :smile:

**Comment by zdila** [comment]
nevidno? :)

**Comment by jose1711** [comment]
perfekt, dakujem!
