### ISSUE TITLE
Indicate oneway=yes

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-mapnik#214]

**Comment by grinapo** [comment]
I would suggest to reopen, since layer=X still cries for the arrows. It is the default layer and I honestly wasn't even aware of layer=T....

**Comment by zdila** [comment]
No reason to reopen as it is fixed, just not deployed yet.

**Comment by zdila** [comment]
layer=T is legacy - hiking only, slovakia only, less precise hill shading and coutours with many faults, no hi-res, daily updated (not minutely), labels and pois are updated actually ad hoc (couple of times a year?), no hi-res export for printing, not developed anymore...
