### ISSUE TITLE
nazov uvedeny v tagu name:sk by mal mat prednost pred name

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-mapnik#223]
Myslim, ze v pripade, ze ma ten isty objekt `name` aj `name:sk`, hodnota v `name:sk` by mala mat prednost. Tym by sa predislo nasledovnym situaciam:
![obrázok](https://user-images.githubusercontent.com/1406222/150818910-f29b16fc-0682-4d14-bd7c-11ebb8ddeebd.png)
(https://www.freemap.sk/?map=17/48.755248/17.812121&layers=X)

![obrázok](https://user-images.githubusercontent.com/1406222/150819132-b6526afb-8790-4a5a-99d3-71fdebf96e03.png)

**Comment by zdila** [comment]
Outdoor mapa nie je urcena primarne pre slovenskych pouzitatelov ale je medzinarodna. Rovnako ako default (carto) vrstva na osm.org. Preto tagy s language prefixom neriesi.
