### ISSUE TITLE
Slovinske LIDAR data pre X vrstvu

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-mapnik#224]
Podla info na stranke [Ministrstvo za okolje in prostor](http://www.evode.gov.si/index.php?id=69) su LIDAR data pre Slovinsko volne dostupne. Aj diskusie na Slovinskych forach toto naznacuju.

Kedze freemap pouzivaju aj pouzivatelia zo Slovinska, asi by ocenili podrobnejsie vrstevnice a tienovanie v X vrstve. Okrem vyssie uvedeneho linku som nasiel tieto zdroje info, ktore by mohli pomoct pri implementacii:

https://github.com/nejcd/LidarSloveniaDataDownloader
https://paleoseismicity.org/tutorial-how-to-make-a-dem-from-the-slovenian-lidar-data/

**Comment by zdila** [comment]
@alexanderzatko skus sa pripadne spytat na Slovinskych forach ci poskytnu DEM alebo ASC data pre ucely X. Mozno ich uz tam niekto ma.

**Comment by alexanderzatko** [comment]
https://forum.openstreetmap.org/viewtopic.php?id=75260

pridam sem komentar s vysledkom
