### ISSUE TITLE
3 a viac ikonky pre jedno POI

### ISSUE THREAD

**Issue by Filip10** [FreemapSlovakia/freemap-mapnik#226]
https://www.freemap.sk/?map=19/48.658300/20.600443&layers=X
https://www.freemap.sk/?map=20/48.665740/20.534072&layers=X
https://www.freemap.sk/?map=20/48.610841/20.874730&layers=X

**Comment by zdila** [comment]
Vdaka za report!

**Comment by Filip10** [comment]
Na zoome 14 sú stále 3, na ostatných je to už okej.

**Comment by zdila** [comment]
Casom, po prerenderovani, zmiznu.

**Comment by zdila** [comment]
odlozim si tu jeden sql `select distinct '14/' || floor(16384 * (st_x(pt)+180)/360) || '/' ||  floor(16384 * (1 - (ln(tan(radians(st_y(pt))) + 1/cos(radians(st_y(pt)))) / pi())) / 2) from (select ST_Transform(st_centroid(geometry), 4326) as pt from osm_feature_polys where osm_id < 0) aa;`
