### ISSUE TITLE
Render cyklotrasy v Maďarsku

### ISSUE THREAD

**Issue by Filip10** [FreemapSlovakia/freemap-mapnik#231]
https://wiki.openstreetmap.org/wiki/Hungary/Ker%C3%A9kp%C3%A1r%C3%BAt#jel.3D.2A_jelz.C3.A9sek
**jel=***
jel=kmtb - modrá
jel=pmtb - červená
jel=smtb - žltá
jel=zmtb - zelená

**Comment by zdila** [comment]
neviem ci chceme podporovat lokalne znacky, za mna skor nie. nech si radsej pridaju tag `colour`.

**Comment by zdila** [comment]
pozri tiez #232

**Comment by Filip10** [comment]
duplicate #188
