### ISSUE TITLE
rendering problem v Slovinsku

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-mapnik#239]
StefanB na Slovinskom fore reportoval problem pri rendrovani:

https://forum.openstreetmap.org/viewtopic.php?pid=860032#p860032

**Comment by zdila** [comment]
vsimol som si, ale nemozu mat vsetko :)

**Comment by zdila** [comment]
opravene na coastline (este sa to dorenderuje). pri pobrezi, trochu hlbise v krajne, na riekach a mkoradiach to este je, ale to uz riesit, vzdladom na narocnost, nebudem.

**Comment by stefanb** [comment]
Thanks, it is much better than it was!
