### ISSUE TITLE
rendering of forests/woodland and scrubs

### ISSUE THREAD

**Issue by dp7x** [FreemapSlovakia/freemap-mapnik#240]
Hello
I would like to suggest to change rendering style for scrubs (natural=scrub). They actually have a pattern and the color is darker then forests (landuse=forests) and woodland (natural=wood). So when you look at the map, you're led to think that there is a deeper forest instead of a light one. I would suggest to make scrubs lighter, like it's rendered in basic OSM; or, on the contrary, to make forests and woodlands darker, maybe with a pattern.

I try to explain with some pictures.

This shows a satellite view of a forest with a scrub in the middle.
![image](https://user-images.githubusercontent.com/103643938/165542568-c8a910d8-673f-4b97-8e3f-42509b6dcf12.png)

This is how it's rendered in OSM: the scrub is lighter:
![image](https://user-images.githubusercontent.com/103643938/165542996-bd6b05ea-10f9-4469-ab14-61e127a3a640.png)

This is how it's rendered in freemap: the darker color makes me think that there is a forest in the middle and the scrub or a grassland is out of it.
![image](https://user-images.githubusercontent.com/103643938/165543231-867fd2c2-5799-4528-9e18-0509218371d9.png)

I hope you understand what I mean... please let me know if it's not clear !
Thank you

**Comment by zdila** [comment]
Thanks for the report, I will consider this.

**Comment by zdila** [comment]
In any case I am against pattern on forests as they cover most of the land and it would clutter the map.

**Comment by dp7x** [comment]
I agree with you about patterns. In this case, I think that changing the color of scrubs, making it lighter that forests (and still darker than grass and farmland), would be enough.

**Comment by zdila** [comment]
Sample: ![image](https://user-images.githubusercontent.com/636095/167389063-ba616a0f-00ff-4f3d-9e8e-ad980c6eb8d6.png)

You will see the changes after the deployment (within couple of days).
