### ISSUE TITLE
rendering of trees / natural monuments

### ISSUE THREAD

**Issue by dp7x** [FreemapSlovakia/freemap-mapnik#244]
Hello
Could you please render points tagged as NATURAL=TREE ?
You could also use a different rendering according to the leaf type. In basic OSM they are rendered like this:
![image](https://user-images.githubusercontent.com/103643938/169068763-2787578a-20e1-4144-89e4-295f9ba1e67a.png)
(this could be a good idea also for the rendering of forest, maybe with a very light pattern)

Also, you could use a different rendering for the additional tag DENOTATION=NATURAL_MONUMENT , with the same icon inside a circle. Something like this:
![image](https://user-images.githubusercontent.com/103643938/169072838-3c62763b-03e6-4af3-8e5f-51ae2a726359.png)
One of the two could be used if leaf tag is missing.

Go hiking to find natural monuments is a very fulfilling activity and this information would be very useful on Freemap. 
(If you want, take a look here: https://www.monumentaltrees.com/en/ . This is a very old portal, but still very useful)

**Comment by zdila** [comment]
Trees are already rendered, see https://www.freemap.sk/?map=19/48.705852/21.236692&layers=X for regular trees and https://www.freemap.sk/?map=19/48.821129/20.989133&layers=X for protected trees, maybe we could include natural monuments there too.

**Comment by dp7x** [comment]
Hello Martin, any news about this topic ? 
Could you include also natural monuments trees in the render ?
Thanks

**Comment by zdila** [comment]
Hi. Currently I have not much time for freemap...

**Comment by dp7x** [comment]
Ok, the rendering for protected trees is good, please include also natural monumets.
It’s important they are rendered also when inside forest areas.
Thank you !




Il giorno 18 mag 2022, alle ore 18:36, Martin Ždila ***@***.***> ha scritto:

﻿

Trees are already rendered, see https://www.freemap.sk/?map=19/48.705852/21.236692&layers=X for regular trees and https://www.freemap.sk/?map=19/48.821129/20.989133&layers=X for protected trees, maybe we could include natural monuments there too.

**Comment by zdila** [comment]
natural monument trees are visible - https://www.freemap.sk/#map=17/48.660550/18.608582&layers=X&tool=objects

**Comment by dp7x** [comment]
Hello Martin
Great work!
Thank you

Diego

Il giorno 11 ott 2022, alle ore 11:25, Martin Ždila ***@***.***> ha scritto:

﻿

natural monument trees are visible - https://www.freemap.sk/#map=17/48.660550/18.608582&layers=X&tool=objects
