### ISSUE TITLE
render route=running

### ISSUE THREAD

**Issue by lucgential** [FreemapSlovakia/freemap-mapnik#250]
In France we have trail running routes (with markers), and I would suggest that [www.freemap.sk](http://www.freemap.sk/) could render it, together with hiking routes. OsmAnd recently have added support for running routes. In the simplest case you could render running routes in the same way as hiking routes. Mappers are tempted to use the route=hiking tag in the absence of rendering of running routes (there are indeed more running routes in OSM than we think) or sometimes route=running;hiking which is rarely supported in applications.

Example 1:
https://hiking.waymarkedtrails.org/#route?id=14352026&type=relation
https://www.valmorel.com/en/summer-activities/hiking-trail/trail-valmorel/

Example 2:
https://www.openstreetmap.org/relation/11922931

**Comment by pyrog** [comment]
FI: Waymarked Trails support multi values for the key `route` (but don't render yet `route=running`)

**Comment by lucgential** [comment]
Thank you @zdila for the commit. Can you tell us if the change is already visible in either freemap.sk or next.freemap.sk (which I guess is the development version of the map)?

**Comment by zdila** [comment]
It is not. I only added mapping to yaml file for possible future implementations.

**Comment by zdila** [comment]
Implemented - now it should render as route=hiking or route=foot.

Due to the later fix in the mapping the routes will appear after reimport or if a route is modified.
