### ISSUE TITLE
Allow switching language for map lables

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-mapnik#256]
To make the map more usable outside Slovakia, it should be possible to present map features labels in a language auto-detected (by geolocated IP address), and ideally also allow users to switch language arbitrarily.

**Comment by zdila** [comment]
freemap-mapnik is about raster maps where this is difficult to implement. if there were vector maps it would be very easy.

**Comment by zdila** [comment]
Closing as out-of scope for raster map. On www.freemap.sk we have now also two vector maps which have this feature. See also FreemapSlovakia/rustmap#49
