### ISSUE TITLE
prevent rendering small landuse=military on low zooms

### ISSUE THREAD

**Issue by Filip10** [FreemapSlovakia/freemap-mapnik#271]
or set line opacity to lower.

**Comment by zdila** [comment]
example?

**Comment by Filip10** [comment]
https://www.freemap.sk/#map=10/48.695493/21.215973&layers=X&line=48.577516/20.341187%2C48.542069/20.299988%2C48.512056/20.396118%2C48.566612/20.423584%2C48.591143/20.348053&line=48.613846/21.119843%2C48.577516/21.114349%2C48.584784/21.184387%2C48.644706/21.188507%2C48.632909/21.112976&line=49.059470/21.339569%2C49.038768/21.229706%2C48.992834/21.173401%2C49.000943/21.280518%2C49.037868/21.358795%2C49.066668/21.358795&line=48.677360/20.545807%2C48.641984/20.467529%2C48.611122/20.522461%2C48.647428/20.565033%2C48.673733/20.569153
