### ISSUE TITLE
Export for only cycleroutes not working properly

### ISSUE THREAD

**Issue by Filip10** [FreemapSlovakia/freemap-mapnik#272]
![obrázok](https://user-images.githubusercontent.com/25711588/202896792-58e4e60e-7aab-4416-9e95-99c856bb0fab.png)
![obrázok](https://user-images.githubusercontent.com/25711588/202896784-e308ae53-86bc-48e1-8348-7da8e36d7396.png)

**Comment by zdila** [comment]
b0cf3e42662622f85aa4de7501f40161a1cf3ff7
