### ISSUE TITLE
Nastavenie máp v dolnej liste asi BUG

### ISSUE THREAD

**Issue by IvanSipka** [FreemapSlovakia/freemap-mapnik#273]
Nazdar Martin, popíšem problém ktorý mám možno len ja ale keďže som to skúšal aj na iných PC, prehliadačoch aj kontách tak to bude všeobecná chyba v systéme :-)

Ak do dolnej lišty cez "tri bodky" a následné "nastavenie  máp" pridám mapu do lišty/menu
 tak ju tam pridá v poriadku (Zmeny boli uložené.) Ale po následnom opustení stránky a vrátení sa naspäť (príp. refresh F5) tak 
menu a lišta je zasa v pôvodnom stave teda bez pridanej mapy.
POZOR takto sa to správa len keď som prihlásený, v odhlásenom móde to funguje OK.

S pozdravom Ivan.

**Comment by IvanSipka** [comment]
... až dnes som si všimol že sú tu aj iné sekcie a ja som pridal tento problém do nesprávnej.
Napísal som ho aj do tej správnej ale tu ho neviem zmazať.
Ivan.

**Comment by zdila** [comment]
nemusel si vytvarat novy, ja by som ho presunul.
