### ISSUE TITLE
Cycle trails have a duplicated rendered name

### ISSUE THREAD

**Issue by BelKed** [FreemapSlovakia/freemap-mapnik#275]
As the title says, cycle trails have a duplicated rendered name. One name is from a parent relation, and the other is from the way.

---

<p align="center">
<img width="464" alt="Screenshot" src="https://user-images.githubusercontent.com/66956532/210422050-8df7b156-6c31-4913-9c3d-ca2e5cba3a3e.png">
</p>
<p align="center">
<sup><a href="https://www.freemap.sk/#map=16/48.743661/21.175890&layers=X"><code>https://www.freemap.sk/#map=16/48.743661/21.175890&layers=X</code></a></sup>
</p>

**Comment by tjamecny** [comment]
Keď je bordel v OSM dátach, tak bude bohužiaľ bordel aj na vyrenderovanej mape.
Napr.:
1) chodníky v lese nemajú oficiálne mená. To, čo je tam teraz zaznačené je výmysel pár jednotlivcov a nejedná sa o meno chodníka, ale o názov miestnej cyklotrasy. Preto patrí daný názov iba do relácie.
2) pravdepodobne v teréne nie je žiadna tabuľka s názvom, lebo relácia má iné meno ako "meno" lesného chodníka.

Riešenie tohto problému je vymazať zbytočné tagovanie z highway=* a ponechať ho len na reláciách. S renderovaním to nemá nič spoločné.

**Comment by BelKed** [comment]
Vďaka za info :)
