### ISSUE TITLE
render building=ruins as ruins

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-mapnik#277]

**Comment by alexanderzatko** [comment]
suggestions attached, svg version provided
![b-r-mock](https://user-images.githubusercontent.com/3430677/233544252-85593db5-cc6a-48e3-9fb4-dc572e285f0f.jpg)
[building-ruins.svg.zip](https://github.com/FreemapSlovakia/freemap-mapnik/files/11292329/building-ruins.svg.zip)

**Comment by zdila** [comment]
(slightly) duplicates #285

**Comment by alexanderzatko** [comment]
dakujem
