### ISSUE TITLE
Add highres hillshade in France as in Switzerland

### ISSUE THREAD

**Issue by lucgential** [FreemapSlovakia/freemap-mapnik#297]
Hi all, 
You already implemented high resolution hill shading in Switzerland. There is something similar in France with the SCAN25TOUR_PYR-JPEG_WLD_WM layer from https://wxs.ign.fr/YOUR_KEY/geoportail/r/wms?SERVICE=WMS? The state of the art DEM from IGN is now RGE ALTI® 1M. Documentation here: https://geoservices.ign.fr/rgealti and https://geoservices.ign.fr/documentation/donnees/alti/rgealti
<img width="1680" alt="image" src="https://github.com/FreemapSlovakia/freemap-mapnik/assets/46304787/4c5d91c0-b908-4736-beb3-9e0116a7d506">

**Comment by zdila** [comment]
Thank you. I will put it to my long TODO priority queue.

**Comment by zdila** [comment]
Used RGE ALTI® 5M.

Note that RGE ALTI® 1M would require much more volume to download and process but would bring no remarkable improvements as it often contains only upscaled data from the lower resolution.

Announcement: https://www.facebook.com/FreemapSlovakia/videos/1509729739568972/

Please support us at https://www.freemap.sk/#show=supportUs and/or propagate our maps.
