### ISSUE TITLE
Cave not showing up

### ISSUE THREAD

**Issue by matic13** [FreemapSlovakia/freemap-mapnik#300]
Hi,

for some reason this cave doesn't show up on the map - it only shows when you look it up by name: https://www.freemap.sk/#map=18/46.290244/15.133259&layers=X&osm-node=455695504

https://www.openstreetmap.org/node/455695504#map=18/46.29005/15.13469&layers=N

Please can you check?

**Comment by zdila** [comment]
Thanks for the report! It should be fixed now.
