### ISSUE TITLE
Documentation : Missing instructions about systemd services

### ISSUE THREAD

**Issue by necarnot** [FreemapSlovakia/freemap-mapnik#308]
./doc/INSTALL.md is stating to stop / start imposm3 and / or freemap-mapnik-prerender systemd services but these services don't exist in common systems.

The FreemapSlovakia team provides them in ./etc/systemd folders, and they have to be put into the relevant folders, then they have to be adapted (username, password, database name, working folder) and systemd daemon has to be reloaded.

If you prefer, tell me if you'd like me to post a PR about this point in ./doc/INSTALL.md ?

**Comment by zdila** [comment]
Hi. PR is welcome.

**Comment by nicolas-ecarnot-sitpi** [comment]
OK Martin,
I'm preparing a PR.

Just a question about `systemctl stop freemap-mapnik-ondemand` : what does this "ondemand" comes from?
The actual file does  not contain "ondemand". Is it a systemd specific keyword or what?

**Comment by zdila** [comment]
On our servers we run 2 instances of the service:

- ondemand - renders tile if it is requested by user (to zoom 19) and is missing
- pre-render - pre-render tiles to zoom 14 (if tile is missing or OSM data has been changed)

This does not need to be covered in this repo so feel free to remove `-ondemand` suffix.

**Comment by zdila** [comment]
Actually the documentation is kind of mix of internal notes and normal documentation :-)

**Comment by necarnot** [comment]
Yep Martin, I understand.
My PR is ready, but I found interesting to add a little bit of your explanation about the two types of rendering services.
As I don't know any much, this PR is just a first step, because I'm self-learning how to use and install this project.
I'm facing lots of issues, and I'd rather share my findings with other by enhancing the documentation.

**Comment by zdila** [comment]
We have it separated only to run them with different priority (nice) - we want ondemand to have higher prio than pre-render. You can also see in service file `FM_CUSTOM_SQL="set_backend_priority(pg_backend_pid(), 10),` which changes also priority of postgis query execution.

**Comment by zdila** [comment]
Just being curious - what is your intent of having your own freemap-mapnik instance running?

**Comment by nicolas-ecarnot-sitpi** [comment]
I'm taking part in a mountain sport website which is using google maps layers at present.
Issues are : 
- this is not free
- these maps are terrible for mountain sports, because their precisions are bad
- lots of elements are lacking to help people find their way
- We don't need to cover the whole world, so I believe in a home-made tile server of chosen zones, both pre and on-demand rendered, hosted on our own.

After tons of research amongst projects, I found yours was light-years ahead in terms of readability and clarity of maps, especially in the contours and hillshading matters. I'm still learning, so I may ask stupid questions.
So I thought it would be helpful to other to improve the doc along this bumpy road.

**Comment by necarnot** [comment]
I'm taking part in a mountain sport website which is using google maps layers at present.
Issues are :

- this is not free
- these maps are terrible for mountain sports, because their precisions are bad
- lots of elements are lacking to help people find their way
- We don't need to cover the whole world, so I believe in a home-made tile server of chosen zones, both pre and on-demand rendered, hosted on our own.

After tons of research amongst projects, I found yours was light-years ahead in terms of readability and clarity of maps, especially in the contours and hillshading matters. I'm still learning, so I may ask stupid questions.
So I thought it would be helpful to other to improve the doc along this bumpy road.
