### ISSUE TITLE
Postgis authentication method failing

### ISSUE THREAD

**Issue by necarnot** [FreemapSlovakia/freemap-mapnik#315]
When launching the freemap-mapnik service, amongst the starting logs, I see that error:

```
déc. 29 11:29:04 freemap node[10097]: Error creating or configuring Mapnik: [Error: Postgis Plugin: authentication method 10 not supported
déc. 29 11:29:04 freemap node[10097]: Connection string: 'host=localhost port=5432 dbname=freemap user=freemap connect_timeout=4 fallback_application_name=mapnik'
déc. 29 11:29:04 freemap node[10097]:   encountered during parsing of layer 'Unnamed' in Layer]
```

After that, the log keeps scrolling, and any attempt to create tiles does nothing.
I'm using preview.html and I see in the logs that the GET queries are received and understood by the service, but that does not produce any tiles.

Part of my config file is as such:
```bash
freemap@freemap:/data$ head -n 12 freemap-mapnik/config/development.json5 
{
  db: {
    type: "postgis",
    host: "localhost",
    port: 5432,
    user: "freemap",
    dbname: "freemap",
    password: "freemap",
    estimateExtent: false,
    extent: "-675094.279800,4364860.674692,3339266.226366,6799780.912846",
    max_size: 32,
  },
```

**Comment by zdila** [comment]
Downgrade `password_encryption` in PostgreSQL to `md5`, changing all the passwords and using the md5 authentication method. Or try to update libraries.

**Comment by necarnot** [comment]
Downgrading as you advised did the trick.
Thank you Martin.
