### ISSUE TITLE
Tile server performance

### ISSUE THREAD

**Issue by pdrhlik** [FreemapSlovakia/freemap-mapnik#324]
Hi,

First of all, thanks for such a great work. I am currently in a process of integrating this map into my project because I need my own tile server. I made everything work quite effortlessly (except for hillshading and contours, hope to make it work soon). I'm just curious about how to improve performance.

I tried increasing some Postgres values to utilize my whole server. I have a 4 CPU 3.2 GHz, 32 GB RAM setup and the rendering of new tiles seems really slow (seconds per tile). I only changed `pngquantOptions` and `prerender` to `null` in the config.

Do you have any recommendations? I also tried running [openstreetmap-tile-server](https://github.com/Overv/openstreetmap-tile-server) which is very easy to setup. It uses mod_tile under the hood and it seemed really fast compared to your server solution.

Thanks a lot for any advice,
Patrik

**Comment by zdila** [comment]
You probably used openstreetmap-tile-server with their styles and DB schema.

Try to check what takes most of CPU. Is it Postgres or Node process? If Postgres then try to log slow SQL queries.

**Comment by pdrhlik** [comment]
Node is running at full CPU capacity all the time. Whenever I move the map to render tiles, a few postgres processes are spawned but they seem to do their work fine. Is the node process supposed to behave like this?

**Comment by zdila** [comment]
node process uses mapnik to render the map and mapnik executes query on postgres to get the data. It should not be that slow. MAybe try to add some measutements to the code how long does it take to tender a tile (with mapnik).

**Comment by pdrhlik** [comment]
I'll give it a shot and I'll let you know if I figure something out. Thanks!

**Comment by pdrhlik** [comment]
I eventually took a completely different approach without mapnik so I wasn't able to determine the underlying issue (if there even was one).

Thanks anyway, @zdila!
