### ISSUE TITLE
Style development workflow

### ISSUE THREAD

**Issue by pdrhlik** [FreemapSlovakia/freemap-mapnik#325]
What is the best way to develop the underlying map style? Do you just edit the code or do you use any kind of a style editor? I know that there are editors like [kosmtik](https://github.com/kosmtik/kosmtik), [TileMill](https://github.com/tilemill-project/tilemill) or [Maputnik](https://maputnik.github.io/). Each of these work with a different style format but none seem to fit your style, at least not right out of the box.

I'd like to modify some aspects of your style but I'm not sure what might be the best way to do that in a productive manner. Any suggestions would be very appreciated :-)

Cheers,
Patrik

**Comment by zdila** [comment]
Just edit the code. We use [JsxNik](https://github.com/FreemapSlovakia/jsxnik) which is something like a combination of Mapnik XML and JSX.

Note that there is a plan to abandon this project in favor of https://github.com/FreemapSlovakia/rustmap (where one would need to know Rust and Cairo to style the map).

**Comment by pdrhlik** [comment]
Thanks for the info. So If I invest some time to set up the server using current styles, will a migration to the new project be possible? I'm currently trying to find an optimal solution for running a tile server with a nice map style that emphasizes hiking trails and mountains. Yours is almost perfect for that use case.

Unfortunately I don't know Rust at all, otherwise I might even be able to help out a bit.

**Comment by zdila** [comment]
Migration will mean rewriting your changes to rust. Amount of work will depend on volume of your changes. You can check the source code of rustmap to see how it is used to render the map. It is not that difficult and no big rust proficiency will be required if one would only want to work with the styling.

**Comment by pdrhlik** [comment]
Great, thanks for the info and good luck with the rewrite!
