### ISSUE TITLE
Render historic=ruins

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-mapnik#42]
### way 
teraz sa nerendruje nic:
https://www.freemap.sk/?map=19/48.554964/17.536319&layers=X
https://www.openstreetmap.org/way/51379212

podla mna by sa to mohlo rendrovat rovnakym vzhladom ako building.

### node 
rendroval by som poi ikonu zrucaniny.

**Comment by zdila** [comment]
historic=ruins som videl napr aj na bunkroch. Bolo by vohdne zohladnovat tag ruins=... a historic=ruins by bol fallback s najnizsiou prioritou.
