### ISSUE TITLE
render z12 highways the same as z11

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-mapnik#43]
on zoom 12 (maybe 13) do not render hiighway=* (similar to z11)

**Comment by zdila** [comment]
Mne je prakticke vidiet siet lesnych ciest a chodnikov v ramci casti pohoria. Taky sposob mi pomaha planovat zvolit miesto vyletu/prechadzky (kedze chodim uz hlavne mimo turisticke chodniky). Navrhujem hlasovanie.

**Comment by kaylesk** [comment]
No na Z12 by ešte snáď nemuselo byť, ale Z13 už áno. Teda hovorím o path ale aj track. Ale footway na vyššom Z, pretože sú tam väčšinou iné cesty a bude to preplnené (si myslím)

**Comment by zdila** [comment]
Ja ti neviem - porovnaj (obe Z12):

![image](https://user-images.githubusercontent.com/636095/51665288-b6ef6b00-1fbb-11e9-99d9-a5eefdb1c38c.png)

![image](https://user-images.githubusercontent.com/636095/51665398-f74ee900-1fbb-11e9-9554-ba7a726303a5.png)

Ta druha mapa je prazdna a velmi mi v nej chyba siet polnych ciest. Takze za mna silny nesuhlas.

**Comment by kaylesk** [comment]
Nooo... keď tak na to pozerám, tak teda ten track by tam snáď asi aj mohol byť. 
Máš pravdu. :)

**Comment by MichalPP** [comment]
a stred kosic ako vyzera?

**Comment by zdila** [comment]
> a stred kosic ako vyzera?

Irelevantne na outdoorovej mape. A highway=track v meste velmi nemame :-)

**Comment by zdila** [comment]
Este k tym mestam - tam sa ocakava ze je to huste a preto si bystry pouzivatel tu mapu tam priblizi.

**Comment by MichalPP** [comment]
ak si dobre pamatam, tak hlavna vyhoda mapniku je, ze funguje na z17-z20. a to clovek pouziva najma v meste, takze musi dobre vyzerat aj v meste aj na z14.

**Comment by zdila** [comment]
Tak si vyber, ci ma dobre vyzerat v meste, alebo v horach.

**Comment by zdila** [comment]
A ako som pisal, ked odstranim z z14 track a path, tak mesta to takmer neovplyvni.

**Comment by MichalPP** [comment]
ok, takze spresnim:
na z12 nerenderovat residential,living_street,footway
?

**Comment by zdila** [comment]
> na z12 nerenderovat residential,living_street,footway

to mozem skusit

**Comment by zdila** [comment]
Nevyzera to dobre:

Pred:

![image](https://user-images.githubusercontent.com/636095/51705156-22b4f080-201b-11e9-8108-83bd7ad506a4.png)

Po:

![image](https://user-images.githubusercontent.com/636095/51705087-fbf6ba00-201a-11e9-94f0-2b258b7a63f7.png)

**Comment by zdila** [comment]
Chodniky od z14 BA pomohli (#44)
