### ISSUE TITLE
z14 do not render footways

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-mapnik#44]
do not renter highway: footway, path on z14

**Comment by zdila** [comment]
Nne osobne pridu path prakticke aj na z14. Navrhujem hlasovanie na issue.

**Comment by zdila** [comment]
> lenze potom je toto (petrzalka) https://www.freemap.sk/?map=12/48.108421/17.124252&layers=X jeden velky hnedy flak

no ved to zodpoveda realite - samy beton a asfalt ;-)

naviac mapa sa sustreduje na turistiku, takze koli mestam by sme prisli o cesty v pohoriach, co zaboli viac.

Mozem ale skusit len schovat footways a steps, hoci OSM ich prestalo odlisovat od paths (bez extra tagov - no casom zohladime aj tie tagy).

**Comment by MichalPP** [comment]
da sa filtrovat ci to je sucastou forestu alebo mimo residential,industrial ?

imho by malo ist doplnit takyto virtualny tag v ramci postgisu:
na lines pridat novy stlpec in_city (pridas?)
after update trigger co ho updatne (ten uz dorobim)

**Comment by kaylesk** [comment]
Podľa mňa path na Z14 je ok, ale footway by mohol byť vyššie.
