### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-mapnik#46]
po spusteni `npm run watch` mi to hadze chyby typu 

`node: bad option: --experimental-worker`

ked ho zmazem, tak 
```
freemap-mapserver/lib/renderrer.js:4
const { rename, mkdir, unlink, stat } = require('fs').promises;
```

a zopar await v `lib/prerenderrer.js`

nechyba tam nejaky npm package co to riesi?

**Comment by zdila** [comment]
A mas NodeJS 10 ako sa pise v requirements?

**Comment by MichalPP** [comment]
az tak som to necital :) `v8.15.0` mam

**Comment by zdila** [comment]
8 je malo :)
