### ISSUE TITLE
Nevýrazné poi atrakcií

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-mapnik#48]
Hvizda pre poi tourism=attraction je dosť nevýrazné bolo by fajn keby bola červená možno väčšia a renderovala sa aj pri menších zoomoch a bol tam aj text.

**Comment by zdila** [comment]
Farby POI su zatial naschval rovnake - cierne, nech z mapy nebude omalovanka. Tag tourism=attraction je dost nestastny, lebo je na vsetkom moznom - kadejakych pomnikoch, kostoloch, sochach, jaskynach. Mapa sa snazi zobrazit ikonu atrakcie len ked nenajde na POI ine tagy.

Takze kedze aj jaskyna/kostol/pamatni je atrakcia, nemozeme vsetko zvyraznit velkym cervenym lebo to strati zmysel :-)
