### ISSUE TITLE
Better distinguish tracktype=G2..G5 

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-mapnik#49]
Martin @zdila, ja osobne mam problem na sucasnej X vrstve odlisit, ci je cesta grade2, alebo grade4.

 co povies na to keby sme ich odlisili poctom svetlych bodiek? grade2 ma dve svetle body, grade3 ma tri, atd.

tu je priklad:
<img width="1022" alt="screenshot 2019-01-27 at 11 00 24" src="https://user-images.githubusercontent.com/225506/51799605-5498a380-2223-11e9-9b39-be6af1200fc1.png">

`highway=track` bez tracktype by som dal ako grade4.

**Comment by zdila** [comment]
Takto teraz cca renderujeme bez tracktype. Mne prave terajsie rozlisenie pride dobre - rozlisuje to pomerom svetlej a tmavej ciary. Kus som sa mu venoval. Tie 1px bodky treba ratat a nie je to hned zrejme z vizualu.

**Comment by zdila** [comment]
A hlavne mi to pride dost bodkate, ako keby sa striedal chodnik a asfaltka.

**Comment by petervojtek** [comment]
mne sucasny styl pride fajn ked porovanam dve a viac ciest - vtedy vidim, ze je jedna horsia ako druha (cize vizualne styl funguje pri "relativnom" porovnani).

ale ked pozriem na jednu konkretnu cestu, tak urcit ci je g2 alebo g3 nie som schopny -- t.j. u mna nefunguje "absolutne".

tento moj navrh riesi prave "absolutny" pohlad.

> pride dost bodkate, ako keby sa striedal chodnik a asfaltka.

vacsina ciest je dost dlhych na to, aby bolo vidiet, ze vzor sa pravidelne opakuje.

**Comment by zdila** [comment]
> tak urcit ci je g2 alebo g3 nie som schopny 

mne pride ze su dost rozdielne:

g2 ma malicke medzery (hlavne voci plnej casti):
![image](https://user-images.githubusercontent.com/636095/51805635-3f963180-2270-11e9-9301-855f29c49ca3.png)

g3 ich uz ma o poznanie vacsie - takmer ako plnu cast:
![image](https://user-images.githubusercontent.com/636095/51805642-576db580-2270-11e9-90fc-6d9654a2ad83.png)


> vacsina ciest je dost dlhych na to, aby bolo vidiet, ze vzor sa pravidelne opakuje

pri mensich zoomoch to bude podla mna dost gulas

**Comment by zdila** [comment]
Je to zjavne subjektivne kedze mne to pride dobre rozlisitelne aj ak nie su vedla seba.

Inac hlavna osm mapa to ma velmi podobne ako nasa X, len vsetky tie ciarky maju trochu dlhsie. 

Paradoxne opentopomap to ma dost na h. kedze tam nerozlisim g3 od d4, a g2 od g3 len ked su fakt pri sebe.

mtbmap.cz to ma tiez podobne ako nasa X, len tie ciary maju hrubsie takze to je este vyraznajsie.

map1.eu to tiez riesi cez ciarky, ale len vyssie grady.

**Comment by zdila** [comment]
...takze mozem skusit jemne predlzit tie segmenty.

**Comment by PaloTT** [comment]
Z pohladu bikera vidim nedostatok novej verzie najma v tom, ze celkovo su lesne cesty nevyrazne a zle viditelne. 
https://www.freemap.sk/?map=15/49.001776/19.224579&layers=T
vs.
https://www.freemap.sk/?map=15/49.001776/19.224579&layers=X

Co sa tyka ich vzajomneho rozlisovania, da sa riesit rozne vykreslovanie aj podla zoomov? 
Napr. 
zoomu <=13    negenerovat 4,5 a chodniky
zoom   14  - len 4 typy ciar:  1+2+service  ;  3+4   ;  5+chodniky   ; cesty bez typu
az od 15 hore rozlisovat vsetky

**Comment by PaloTT** [comment]
Vid tie 2 linky.
v T verzii je to OK - ciary su dostatocne vyrazne - su tmavsie, ?mozno mierne hrubsie?
X verzia ich ma nevyrazne sedo-biele, stracaju sa v mape

**Comment by zdila** [comment]
Mne pridu v T az velmi kontrastne. Ale pokusim sa ich trocha zvyraznit. Inac X vrstva ich ma dohneda, ziadne "sedo-biele".

**Comment by PaloTT** [comment]
A to som chcel povodne napisat,  ze ja by som aj v Tcku  este trochu kontrastu naviac prijal.
Do hneda ... to bude ten problem :)

**Comment by zdila** [comment]
> A to som chcel povodne napisat, ze ja by som aj v Tcku este trochu kontrastu naviac prijal.

Tak to ti treba iny farebny priestor (mimo sRGB) aby si mohol mat ciernejsiu ako ciernu #000000 ;-).

**Comment by zdila** [comment]
...alebo biele lesy.

**Comment by zdila** [comment]
Zal takyto lokalny pokus:

pred:
![image](https://user-images.githubusercontent.com/636095/51867978-24e5ba80-234d-11e9-853b-4b70ae32ca73.png)

po:
![image](https://user-images.githubusercontent.com/636095/51867989-2fa04f80-234d-11e9-9852-53453740590b.png)

**Comment by zdila** [comment]
A este kus tmavsia hneda:
![image](https://user-images.githubusercontent.com/636095/51868133-93c31380-234d-11e9-86b4-ee2272c15632.png)

**Comment by PaloTT** [comment]
Obe urcite lepsie ako teraz. Na tej Smrekovici v zoome 15 by zmena bola asi este zretelnejsie.
Nemaju tie upravene verzie prehodene obrazky?  Verzia "po:" sa mi zda najviac "vyrazna"
resp. su si velmi podobne.

**Comment by zdila** [comment]
> Verzia "po:" sa mi zda najviac "vyrazna"

viac "vyrazna" ako co?

**Comment by zdila** [comment]
> Verzia "po:" sa mi zda najviac "vyrazna" resp. su si velmi podobne.

posledny screenshot ma len trosicku tmavsiu tu hnedu takze ten rozdiel je naozaj minimalny

**Comment by PaloTT** [comment]
Color picker netreba, vyzeras a komunikujes doveryhodne :)

**Comment by petervojtek** [comment]
dnes som zabludil na mape [sem](https://www.freemap.sk/?map=15/48.689470/19.159032&layers=X):

<img width="847" alt="screenshot 2019-01-30 at 07 53 57" src="https://user-images.githubusercontent.com/225506/51963571-5dc48300-2464-11e9-9cf9-95683ccfe388.png">

a zd asa ze su tam dva typy lesnych ciest. je pre mna tazke si vobec odvodit, ktora z nich ma reprezentovat vyssi a nizsi grade level (tusim len podla toho, ze v dolinach je obvykle lepsi grade level nez na hrebenoch). 
 to, o akykonkretny  grade level v jednom a druhom pripade ide, neviem povedat. tiez netusim, ci sa tam nemiesaju `highway=tracktype`, bez uvedeneho grade.

**Comment by petervojtek** [comment]
dalsia diskusia bola cez slack a viedla k nejakym zmenam.. takze uzatvaram tuto zalezitost
