### ISSUE TITLE
Make multiple parallel rail tracks less ugly

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-mapnik#52]
jednotlive kolaje sa zlievaju do ciernej plochy a nevyzera to pekne:

<img width="845" alt="screenshot 2019-01-30 at 08 06 37" src="https://user-images.githubusercontent.com/225506/51964196-15a66000-2466-11e9-9f12-ca41946c1820.png">

https://www.freemap.sk/?map=15/48.578006/18.988090&layers=X

**Comment by kaylesk** [comment]
Tu by možno bolo dobré použiť [service=spur](https://wiki.openstreetmap.org/wiki/Cs:Tag:service%3Dspur) a [service=siding](https://wiki.openstreetmap.org/wiki/Cs:Tag:service%3Dsiding) a zobrazovať ich až napr. od z14 a možno aj mierne užšie/bledšie (skrátka inak). Teda aspoň siding určite, ale spur bude asi na debatu či nie od z13, lebo vlečky sú aj dosť dlhé, tu je napr. časť https://www.openstreetmap.org/way/42211117 čo by bolo asi vhodné vidieť na mape.

**Comment by zdila** [comment]
@petervojtek sorry, az teraz pozeram ze si si to assignol. Ja som medzitym pridal glow:

po:
![image](https://user-images.githubusercontent.com/636095/52040056-8452ee80-2536-11e9-90d1-b5596c50cecc.png)

pred (naviac este s hnedsimi farbami ciest):
![image](https://user-images.githubusercontent.com/636095/52040087-9df43600-2536-11e9-9221-85255c688a8c.png)

@kaylesk Rozlisenie podla typu railway by som asi dal do ineho issue.

**Comment by zdila** [comment]
@petervojtek uzavri ak k tomu uz nic nemas :-)
