### ISSUE TITLE
Rendering landuse=village_green

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-mapnik#61]
Rendering landuse=village_green in some green colour.

**Comment by seg-on** [comment]
It is rejected or accepted? :D
Because I'm not see change on map.

**Comment by zdila** [comment]
Locally?

**Comment by seg-on** [comment]
On freemap.sk
https://www.freemap.sk/?map=18/48.596298/17.818043&layers=X
https://www.freemap.sk/?map=18/48.596298/17.818043&layers=O

**Comment by zdila** [comment]
It is fixed but not released to freemap.sk.

**Comment by seg-on** [comment]
ok. thanks :)
