### ISSUE TITLE
waterfalls are missing from map

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-mapnik#65]
https://www.openstreetmap.org/node/4012582822#map=17/48.42784/18.57486
https://www.freemap.sk/?map=17/48.429489/18.574405&layers=T
https://www.freemap.sk/?map=17/48.429489/18.574405&layers=X

**Comment by zdila** [comment]
see 25ac87ee081ef2655669d5d28fe564bba0026410

**Comment by petervojtek** [comment]
ano, vidim ze kod tam je, ale vodopady nevidim, napr. tieto dva:
https://www.freemap.sk/?map=15/48.984450/19.689415&layers=T

**Comment by zdila** [comment]
Neviem ci je to nasadene. Lokalne ich tiez nevidis (po reimporte extraktu)?

**Comment by petervojtek** [comment]
mas pravdu, je to v mape ale nenasadene na portali.
<img width="611" alt="screenshot 2019-02-23 at 08 40 17" src="https://user-images.githubusercontent.com/225506/53283434-b7a82800-3746-11e9-9f80-01fc9c94ead9.png">
