### ISSUE TITLE
renderovanie železníc

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-mapnik#75]
okolie vlakov vyzerá škaredo ([napr](https://www.freemap.sk/?map=15/48.193771/17.191930&layers=X) [alebo](https://www.freemap.sk/?map=16/48.164186/17.119639&layers=X)) 

po nejaký zoom renderovať iba tie railway, čo nemajú tag service (alebo service=main)

napr `.rule({ maxZoom: 13, filter: "[class] = 'railway' and ( [service] = 'main' or [service] = '' )" })` v index.js (a zmeniť query)

tým by sa tie depá nezobrazovali (alebo im dať menej výrazný symbol)

**Comment by MichalPP** [comment]
vďaka, hneď je to krajšie

ide nejak nastaviť, aby tie service railways vždy zobrazovalo pod hlavnými? lebo niekedy ich prekryjú a potom ich vlastne nevidno.

**Comment by zdila** [comment]
> de nejak nastaviť, aby tie service railways vždy zobrazovalo pod hlavnými?

aj preto tato issue este nie je zatvorena
