### ISSUE TITLE
Render orchards

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-mapnik#78]
farba napriklad #faddbe (ako vidno tu: https://drive.google.com/file/d/16dx-HZLIhjdxUbO_O5RbR7hAgPU5jvld/view?usp=sharing).

**Comment by zdila** [comment]
Orchard sa uz renderuje: https://github.com/FreemapSlovakia/freemap-mapnik/blob/b9209dba7e1a11345fe95d13dcb184b83c1b4f65/style/index.js#L143
Skor treba texturu #77
