### ISSUE TITLE
rendering problem

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-mapnik#79]
na retina display-i su cerstvo editovane oblasti rozbite. Vid tu:
https://www.freemap.sk/?map=14/48.402796/19.209681&layers=X
https://drive.google.com/file/d/1ya0gRaiH_UosglMcmSD_CGbW8x0hrroU/view?usp=sharing

**Comment by zdila** [comment]
vdaka, uz to riesim

**Comment by zdila** [comment]
uz len pockat cca 2 dni na prerenderovanie (alebo na novy sever kde to bude za pol dna)
