### ISSUE TITLE
Chybějící žlutá turistická značka

### ISSUE THREAD

**Issue by vkvkv** [FreemapSlovakia/freemap-mapnik#85]
Okolo šachty vede žlutá značka z Jezeří kolem Žeberské lípy do Vysoké Pece. https://www.freemap.sk/?map=15/50.543231/13.483100&layers=X Bohužel se nevykreslila.
Na osm.org je zadaná relace "Pěší trasa[Ž] 6951 Jezeří - Vysoká Pec" https://www.openstreetmap.org/relation/1826938#map=14/50.5378/13.4822
osmap.cz jí zobrazují. Na relaci mé oko laika nic podezřelého neobjevilo.
Dnes jsem poblíž přidával lesní cestu. https://www.openstreetmap.org/way/696082157#map=18/50.53586/13.46585 Ta je již vykreslená. Netuším, zda to může mít souvislost.

Díky Vašek

**Comment by zdila** [comment]
Vďaka za objavenie celkom slušnej chyby, opravil som. Na mape sa to prejaví keď spravim reimport (v priebehu pár dní).

**Comment by vkvkv** [comment]
Díky.
