### ISSUE TITLE
rozlišení highway=track - tracktype=* a highway=path - trail_visibility=*

### ISSUE THREAD

**Issue by vop-cz** [FreemapSlovakia/freemap-mapnik#89]
navrhuji zavést vizuální rozlišení pro rozdílné kvality cest (track) a pěšin (path):

1) `highway=track` a `highway=path` rozlišit vždy barvou a tloušťkou (track vždy tmavší a vždy 2 x silnější)

2) pro `highway=track` rozlišovat `tracktype=*` typem čar (kombinace světlé podkresové linie s doplňkovými tmavými čárkovanými, čerchovanými či tečkovanými čarami) jako doposud

3) pro `highway=path` rozlišovat `trail_visibility=*` světlostí zobrazené linie (dosud je vždy highway=path zobrazena jen jedním způsobem)

**Comment by zdila** [comment]
`highway=track` a `highway=path` sú odlišené hrúbkou aj prerušovaním:

![image](https://user-images.githubusercontent.com/636095/59267357-4f744800-8c4a-11e9-9c10-7082b7cabd6e.png)
(`highway=path` je ta celkom vpravo)

V teréne je mnoho ciest kde jeden mapper dá `highway=path` a iný by dal `highway=track`, preto ich nechcem rozlišovať ešte dramatickejšie.

**Comment by zdila** [comment]
> pro highway=track rozlišovat tracktype=* typem čar (kombinace světlé podkresové linie s doplňkovými tmavými čárkovanými, čerchovanými či tečkovanými čarami) jako doposud

nerozumiem, treba niečo meniť (keďže toto už je implementované)?

**Comment by vop-cz** [comment]
> highway=track a highway=path sú odlišené hrúbkou aj prerušovaním:
> (highway=path je ta celkom vpravo)

...aha, až teď to vidím... ale i ty jsi musel pro jistotu připsat, že je to "ta celkom vpravo" :) Možná by bylo sympatické, když by ten rozdíl byl podvědomě ještě výraznější. Některá "dobře zmapovaná" uzemí jsou protkaná track i path a vypadají pak zmatečně...

> V teréne je mnoho ciest kde jeden mapper dá highway=path a iný by dal highway=track, preto ich nechcem rozlišovať ešte dramatickejšie.

a není právě tady "zakopaný pes"? Mapper by měl bez zaváhání poznat rozdíl mezi `track` a `path` (když nebudu hledat dokonalou definici, tak rozdílem je "pro vozidlo nebo pro chodce") a měl by to označit správně. Méně zkušení váhají především tam, kde to pak v mapách vidí vyrenderované všechno stejně... Když se podívám do kartograficky správně nakreslených map, tak je `track` od `path` rozlišena záměrně velmi výrazně (je silnější a u podrobnějších zobrazení má světlou linii s tmavými outlines).

> nerozumiem, treba niečo meniť (keďže toto už je implementované)?

Já jsem jen chtěl shrnout tu myšlenku v kontextu "co a jak od sebe odlišit" a celá pointa byla ve využití (zobrazení) tagu `trail_visibility=*`

**Comment by zdila** [comment]
> ale i ty jsi musel pro jistotu připsat, že je to "ta celkom vpravo"

pre mňa je to zrejmé, ja som len suploval legendu mapy, aby si nehľadal napr. ružovú bodkočiarkovanú ako môžeš byť zvyknutý z inej mapy ;-)

> Mapper by měl bez zaváhání poznat rozdíl mezi `track` a `path`

Sám mám toto v teréne problém niekedy rozoznať, keď idem cestou, kde občas vidím dve stopy, no tá jedna občas mizne a tá druhá je trochu viac prešľapaná. Samozrejme, také horské chodníčky sú jasná vec.

**Comment by zdila** [comment]
...ale vyskúšam tie `path` ešte jemnúčko viac odlíšiť

**Comment by zdila** [comment]
trail_visibility bolo medzicasom implementovane (aj na track) a odlisenie path mi pride uz dostacujuce
