### ISSUE TITLE
embankment

### ISSUE THREAD

**Issue by synalik** [FreemapSlovakia/freemap-mapnik#92]
Nedal by sa zobrazovat aj tag "nasyp" ? man_made=embankment
Potom prosim rovnako aj embankment=yes a man_made=dyke

**Comment by zdila** [comment]
Prosim reportuj toto do spravneho projektu: https://github.com/FreemapSlovakia/freemap-mapnik/

**Comment by synalik** [comment]
Martin, chcem popresúvať aj zvyšné 4 pripomienky, našiel som návod: https://help.github.com/en/articles/transferring-an-issue-to-another-repository no nejde mi to - nemám asi oprávnenia.
Môžem ich napísať nanovo? Tie staré neviem vymazať, len dať Close - bude to tak OK? 
Ak máš tip ako to mám popresúvať, daj vedieť. 
Nechcem Ti pridávať robotu, no tie zdvojenia vznikli tak, že si príliš rýchlo reagoval na mnou napísané Issues. Myslel som, že som niečo spravil zle, keď som to tam po chvíli nenašiel. Tak som to napísal zas...Sorry

**Comment by zdila** [comment]
ja to presuniem, len si musim najst cas a chut

**Comment by synalik** [comment]
ok, ostatné už napíšem hádam do správneho projektu
