### ISSUE TITLE
Oznacovat hlavne neznackovane chodniky vyraznejsie

### ISSUE THREAD

**Issue by synalik** [FreemapSlovakia/freemap-mapnik#96]
Oznacovat hlavne neznackovane chodniky viac vyrazne
Cervena:
highway=path
sac_scale=hiking
Vzor stary Freemap: https://www.freemap.sk/?map=17/49.098349/19.286267&layers=T
Modra
highway=path
sac_scale=alpine_hiking
Vzor stary Freemap:
https://www.freemap.sk/?map=17/49.161787/20.139452&layers=T
https://www.freemap.sk/?map=17/49.192441/20.218636&layers=T

_poznámka od - Mirecnet_

**Comment by zdila** [comment]
nesuhlasim
